# Generated by Django 5.1.3 on 2026-02-24 13:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0004_remove_salarystructure_allowances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_processed', models.DateField(default=datetime.date.today)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='salary_pdfs/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.employee')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResource.salarystructure')),
            ],
        ),
    ]
