# Generated by Django 5.1.3 on 2026-02-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0005_processedsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Permission',
        ),
    ]
