# Generated by Django 6.0.2 on 2026-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0014_quotationitem'),
        ('Finance', '0004_remove_invoice_paid_invoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='Finance_inv_status_9e21ee_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='Finance_inv_due_dat_104b35_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['code'], name='Finance_inv_code_459203_idx'),
        ),
    ]
