# Generated by Django 6.0.2 on 2026-03-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterData', '0013_file_item_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_desc', models.CharField(blank=True, max_length=255)),
                ('fcl', models.CharField(blank=True, max_length=100)),
                ('vatable', models.BooleanField(default=False)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterData.client')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterData.currency')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterData.file')),
                ('fpod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpod_port', to='MasterData.port')),
                ('pod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pod_port', to='MasterData.port')),
                ('pol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pol_port', to='MasterData.port')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterData.supplier')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterData.transport')),
            ],
        ),
    ]
