# Generated by Django 6.0.2 on 2026-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
