# Generated by Django 6.0.2 on 2026-03-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0002_quotation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='description',
            new_name='consignment',
        ),
    ]
