# Generated by Django 6.0.2 on 2026-03-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0004_quotation_grand_total_alter_quotation_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='consignment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
