# Generated by Django 6.0.2 on 2026-03-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0006_alter_quotation_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='description',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='consignment',
            field=models.TextField(blank=True),
        ),
    ]
