# Generated by Django 6.0.2 on 2026-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0007_remove_quotation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='vatable',
            field=models.BooleanField(default=True),
        ),
    ]
