# Generated by Django 6.0.2 on 2026-03-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0008_alter_quotation_vatable'),
        ('MasterData', '0013_file_item_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MasterData.item'),
            preserve_default=False,
        ),
    ]
