# Generated by Django 6.0.2 on 2026-03-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0010_remove_quotation_item_remove_quotation_quantity_and_more'),
        ('MasterData', '0013_file_item_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
        migrations.AddField(
            model_name='quotation',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MasterData.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
