# Generated by Django 6.0.2 on 2026-03-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0011_remove_quotation_items_quotation_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
