# Generated by Django 6.0.2 on 2026-03-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Relation', '0012_remove_quotation_item_remove_quotation_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
    ]
